generator:
  class: sfPropelGenerator
  param:
    model_class:           payment
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              payment
    plural:                payments
    route_prefix:          payment
    with_propel_route:     1
    actions_base_class:    sfActions
    peer_method:           doSelectJoinAll


    config:
      actions: ~
      fields:
        date:
          format_date: D
      list:
        display: [creditor, contract, payment_type,  date, amount, bank_account, sender_bank_account, cash, note]
        batch_actions: []
        sort: [date, asc]
        actions:
          _new: ~
          filters: ~
          reset: ~
          print: ~
      filter:  ~
      form:
        actions:
          _save: ~
      edit:    ~
      new:     ~
