gift:
  class: sfPropelRouteCollection
  options:
    model:                gift
    module:               gift
    prefix_path:          /gift
    column:               id
    with_wildcard_routes: true
    collection_actions: {filters: get, filter: post, reset: get}

allocation:
  class: sfPropelRouteCollection
  options:
    model:                allocation
    module:               allocation
    prefix_path:          /allocation
    column:               id
    with_wildcard_routes: true
    collection_actions: {filters: get, filter: post, reset: get}

outgoing_payment:
  class: sfPropelRouteCollection
  options:
    model:                outgoingPayment
    module:               outgoingPayment
    prefix_path:          /outgoingPayment
    column:               id
    with_wildcard_routes: true
    collection_actions: {filters: get, filter: post, reset: get}
    object_actions: {note: get, detail: get}

bank_account:
  class: sfPropelRouteCollection
  options:
    model:                bankAccount
    module:               bankAccount
    prefix_path:          /bankAccount
    column:               id
    with_wildcard_routes: true
    collection_actions: {filters: get, filter: post, reset: get}
    
currency:
  class: sfPropelRouteCollection
  options:
    model:                currency
    module:               currency
    prefix_path:          /currency
    column:               code
    with_wildcard_routes: true
    collection_actions: {filters: get, filter: post, reset: get}
    
unpaid:
  class: sfPropelRouteCollection
  options:
    model:                unpaid
    module:               unpaid
    prefix_path:          /unpaid
    column:               id
    with_wildcard_routes: true
    collection_actions: {filters: get, filter: post, reset: get}

ip_address:
  class: sfPropelRouteCollection
  options:
    model:                ipAddress
    module:               ipAddress
    prefix_path:          /ipAddress
    column:               id
    with_wildcard_routes: true
    collection_actions: {filters: get, filter: post, reset: get}

regulation:
  class: sfPropelRouteCollection
  options:
    model:                regulation
    module:               regulation
    prefix_path:          /regulation
    column:               id
    with_wildcard_routes: true
    collection_actions: {filters: get, filter: post, reset: get}

security_user:
  class: sfPropelRouteCollection
  options:
    model:                securityUser
    module:               securityUser
    prefix_path:          /user
    column:               id
    with_wildcard_routes: true
    collection_actions: {filters: get, filter: post, reset: get}

payment:
  class: sfPropelRouteCollection
  options:
    model:                payment
    module:               payment
    prefix_path:          /payment
    column:               id
    with_wildcard_routes: true
    collection_actions: {filters: get, filter: post, reset: get}
    object_actions: {note: get}

settlement:
  class: sfPropelRouteCollection
  options:
    model:                settlement
    module:               settlement
    prefix_path:          /settlement
    column:               id
    with_wildcard_routes: true
    object_actions: {capitalize: get, allocate: [get, post], newOutgoingPayment: [get, post], note: get}
    collection_actions: {filters: get, filter: post, reset: get, checkContracts: get, addFilter: get}

creditor:
  class: sfPropelRouteCollection
  options:
    model:                creditor
    module:               creditor
    prefix_path:          /creditor
    column:               id
    with_wildcard_routes: true
    object_actions: {paidDetail: get, giftList: get, addGift: [get, post]}
    collection_actions: {filters: get, filter: post, reset: get}

contract:
  class: sfPropelRouteCollection
  options:
    model:                contract
    module:               contract
    prefix_path:          /contract
    column:               id
    with_wildcard_routes: true
    object_actions: {copy: get, duplicate: post, close: [get, post], note: get}
    collection_actions: {filters: get, filter: post, reset: get, regulation: get}

group:
  class: sfPropelRouteCollection
  options:
    model:                securityGroup
    module:               group
    prefix_path:          /group
    column:               id
    with_wildcard_routes: true
    collection_actions: {filters: get, filter: post, reset: get}


user:
  class: sfPropelRouteCollection
  options:
    model:                securityUser
    module:               user
    prefix_path:          /user
    column:               id
    with_wildcard_routes: true
    collection_actions: {filters: get, filter: post, reset: get}

contract_closing_amount:
    url:   /:id/contract-closing-amount.json
    param: { module: contract, action: closingAmount, sf_format: json }

update_contract_select:
    url:   /:form_name/update-contract-select
    param: { module: contract, action: updateSelect, sf_format: html }

update_settlement_select:
    url:   /:form_name/update-settlement-select
    param: { module: settlement, action: updateSelect, sf_format: html }

update_outgoing_payment_select:
    url:   /:form_name/update-outgoing-payment-select
    param: { module: outgoingPayment, action: updateSelect, sf_format: html }

payment_contract_filter:
  url:   /payment/contract-filter/:contract_id
  param: { module: payment, action: contractFilter }

settlement_contract_filter:
  url:   /settlement/contract-filter/:contract_id
  param: { module: settlement, action: contractFilter }


settlement_interest:
    url:   /settlement-interest.json
    param: { module: settlement, action: interest, sf_format: json }

settlement_balance:
    url:   /settlement-balance.json
    param: { module: settlement, action: balance, sf_format: json }

settlement_close:
  url:   /settlement-close/:contract_id
  param: { module: settlement, action: close }

report_filters:
  url:   /report/:report_type/filters
  param: { module: report, action: filters }

report_filter:
  url:   /report/:report_type/filter
  param: { module: report, action: filter }

report_add_filter:
  url:   /report/:report_type/add-filter
  param: { module: report, action: addFilter }


report_reset:
  url:   /report/:report_type/reser
  param: { module: report, action: reset }

report_sort:
  url:   /report/:report_type/sort/:sort
  param: { module: report, action: sort }

report:
  url:   /report/:report_type
  param: { module: report, action: index }

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
