newSuccess:
  layout: layoutModal

editSuccess:
  layout: layoutModal

copySuccess:
  layout: layoutModal

filtersSuccess:
  layout: layoutModal

detailSuccess:
  layout: layoutModal

ratingsSuccess:
  layout: layoutModal

resultsSuccess:
  layout: layoutModal