generator:
  class: sfPropelGenerator
  param:
    model_class:           unpaid
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              unpaid
    plural:                unpaids
    route_prefix:          unpaid
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        contract_unpaid:
          label: Unpaid
      list:
        object_actions: []
        batch_actions: []
        display: [creditor_fullname, contract_name, contract_unpaid]
        sort: [creditor_fullname, asc]
        actions:
          filters: ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
