generator:
  class: sfPropelGenerator
  param:
    model_class:           subject
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              subject
    plural:                subjects
    route_prefix:          subject
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        birth_date:
          date_format: D
      list:
        batch_actions: []
        display: [subject_type, firstname, lastname, birth_date, email, phone, bank_account, city, street, zip]
        actions:
          _new: ~
          filters: ~
          reset: ~
          print: ~
      filter:  ~
      form:
        actions:
          _save: ~
      edit:    ~
      new:     ~
