generator:
  class: sfPropelGenerator
  param:
    model_class:           settlement
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              settlement
    plural:                settlements
    route_prefix:          settlement
    with_propel_route:     1
    actions_base_class:    sfActions
    peer_method:           doSelectJoinAll

    config:
      actions: ~
      fields:
        translated_settlement_type:
          label: Settlement type
        date:
          date_format: D
      list:
        display: [debtor, creditor,  contract, contract_interest_rate,  date, daysCount,  balance, interest, paid, capitalized, balance_increase, balance_reduction, unsettled, unsettled_cumulative, translated_settlement_type, note]
        batch_actions: []
        actions:
          _new: ~
          filters: ~
          reset: ~
          print: ~
        sort: [date, asc]
        object_actions:
          _edit: ~
          _delete: ~
      filter:  ~
      form:
        actions:
          _save: ~
      edit:    ~
      new:     ~
