generator:
  class: sfPropelGenerator
  param:
    model_class:           settlement
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              settlement
    plural:                settlements
    route_prefix:          settlement
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        date:
          date_format: D
      list:
        display: [contract, date, balance, interest, paid, capitalized, balance_reduction, unsettled]
        batch_actions: []
        actions:
          _new: ~
          filters:
            action: filters
            label: Filters
          reset:
            action: reset
            label: Reset

        sort: [date, asc]
        object_actions:
          _edit: ~
          _delete: ~
      filter:  ~
      form:
        actions:
          _save: ~
      edit:    ~
      new:     ~
