generator:
  class: sfPropelGenerator
  param:
    model_class:           contract
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              contract
    plural:                contracts
    route_prefix:          contract
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at:
          date_format: D
          label: Date of signature
        activated_at:
          date_format: D
          label: Date of activation
      list:
        batch_actions: []
        display: [name, creditor, amount, payments_amount, interest_rate_as_string, period_as_string, created_at, activated_at, closed_at]
        object_actions:
          _edit: ~
          copy:
            action: copy
            label: Copy
          close:
            action: close
            label: Terminate
          _delete: ~
        actions:
          _new: ~
          filters: ~
          reset: ~
          printList:
            action: printList
            Label: Print list
      filter:  ~
      form:
        actions:
          _save: ~
      edit:
        actions:
          _save: ~
#          _save_and_pay_other_contract:
#            Label: Save and pay other contract
#            action: SaveAndPayOtherContract
      new:     ~
