<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/05/24 15:53:59

return array(
'propel' => new sfPropelDatabase(array (
  'dsn' => 'pgsql:host=localhost port=5432 dbname=maur-creditors user=developer password=developer',
  'classname' => 'DebugPDO',
  'debug' => 
  array (
    'realmemoryusage' => true,
    'details' => 
    array (
      'time' => 
      array (
        'enabled' => true,
      ),
      'slow' => 
      array (
        'enabled' => true,
        'threshold' => 0.005,
      ),
      'memdelta' => 
      array (
        'enabled' => true,
      ),
      'mempeak' => 
      array (
        'enabled' => true,
      ),
      'method' => 
      array (
        'enabled' => true,
      ),
      'mem' => 
      array (
        'enabled' => true,
      ),
      'querycount' => 
      array (
        'enabled' => true,
      ),
    ),
  ),
  'name' => 'propel',
)),);
