<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/05/24 15:53:59
sfConfig::add(array(
  'app_registration_mail_subject_en' => '%url% registration',
  'app_registration_mail_message_en' => '<html><body><h3>Your acount on <a href="%url%">%url%</a> was created successfully!</h3><b>password:</b> %password%<br /><br />Best regards<br />Rezervuj.to</body></html>',
  'app_registration_mail_subject_cs' => '%url% registrace',
  'app_registration_mail_message_cs' => '<html><body><h3>Váš účet na <a href="%url%">%url%</a> byl úspěšně vytvořen!</h3><b>heslo:</b> %password%<br /><br />S pozdravem<br />Rezervuj.to</body></html>',
  'app_forgotten_password_mail_subject_en' => '%url% new password',
  'app_forgotten_password_mail_message_en' => '<html><body><br /><b>password:</b> %password%<br /><br />Best regards<br />Rezervuj.to</body></html>',
  'app_forgotten_password_mail_subject_cs' => '%url% nové heslo',
  'app_forgotten_password_mail_message_cs' => '<html><body><br /><b>heslo:</b> %password%<br /><br />S pozdravem<br />Rezervuj.to</body></html>',
  'app_default_currency_code' => 'CZK',
  'app_time_unit_interval' => 1800,
  'app_timetable_time_start' => 32400,
  'app_timetable_time_end' => 79200,
  'app_timetable_days' => array (
  1 => 'mon',
  2 => 'tue',
  3 => 'wed',
  4 => 'thu',
  5 => 'fri',
  6 => 'sat',
  7 => 'sun',
),
  'app_reservation_time_unit_min_count' => 2,
));
