<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/05/24 15:53:59
$this->security = array (
  'rights' => 
  array (
    'credentials' => 'rights.admin',
  ),
  'logout' => 
  array (
    'is_secure' => true,
  ),
  'login' => 
  array (
    'is_secure' => false,
  ),
  'forgottenpassword' => 
  array (
    'is_secure' => false,
  ),
  'registration' => 
  array (
    'is_secure' => false,
  ),
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'error404' => 
  array (
    'is_secure' => false,
  ),
  'filter' => 
  array (
    'is_secure' => false,
  ),
  'filters' => 
  array (
    'is_secure' => false,
  ),
  'reset' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
