generator:
  class: sfPropelGenerator
  param:
    model_class:           regulation
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              regulation
    plural:                regulations
    route_prefix:          regulation
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        contract_id:
          is_link: false
        settlement_year:
          is_link: false
        contract_activated_at:
          date_format: D
      list:
        sort: [contract_id, asc, settlement_year, desc]
        display: [creditor_firstname, creditor_lastname, contract_name, settlement_year, start_balance, contract_activated_at, contract_balance, regulation, paid, paid_for_current_year, capitalized, teoretically_to_pay_in_current_year, end_balance]
        actions:
          filters:
            action: filters
            label: Filters
          reset:
            action: reset
            label: Reset
        batch_actions: []
        object_actions: []
      filter:  ~
      form:
        actions: []
      edit:    ~
      new:     ~
