generator:
  class: sfPropelGenerator
  param:
    model_class:           regulation
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              regulation
    plural:                regulations
    route_prefix:          regulation
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        regulation_year:
          label: Year
        contract_id:
          is_link: false
        settlement_year:
          is_link: false
        contract_activated_at:
          date_format: D
      list:
        peer_method:           doSelectJoinAll
        display: [creditor_fullname, contract_name, regulation_year, start_balance, contract_activated_at, contract_balance, upaid_in_past, regulation, paid, paid_for_current_year, capitalized, unpaid, end_balance]
        actions:
          filters: ~
          reset: ~
          print: ~
        batch_actions: []
        object_actions: []
        sort: [regulation_year, desc]
      filter:  ~
      form:
        actions: []
      edit:    ~
      new:     ~
